import { IHospital } from "@/types";
export const dummyHospitals: IHospital[] = [
  {
    id: 1,
    name: "Alimosho Medical Centre",
    lat: 6.6059,
    lng: 3.2703,
    specialties: ["General Medicine", "Dermatology"],
    averageResponseTime: 35,
    peopleInQueue: 12,
    beds: 80,
    doctors: 25,
    averageConsultancyPrice: 10000,
  },
  {
    id: 2,
    name: "Broadway Hospital Lekki",
    lat: 6.4301,
    lng: 3.5244,
    specialties: ["Pediatrics", "Gynecology"],
    averageResponseTime: 25,
    peopleInQueue: 6,
    beds: 60,
    doctors: 18,
    averageConsultancyPrice: 12000,
  },
  {
    id: 3,
    name: "Clearview Specialist Hospital",
    lat: 6.4541,
    lng: 3.3947,
    specialties: ["Orthopedics", "ENT"],
    averageResponseTime: 40,
    peopleInQueue: 9,
    beds: 50,
    doctors: 15,
    averageConsultancyPrice: 11000,
  },
  {
    id: 4,
    name: "Divine Mercy Hospital Ikeja",
    lat: 6.5969,
    lng: 3.3422,
    specialties: ["Cardiology", "General Surgery"],
    averageResponseTime: 30,
    peopleInQueue: 7,
    beds: 90,
    doctors: 28,
    averageConsultancyPrice: 15000,
  },
  {
    id: 5,
    name: "Evergreen Medical Centre",
    lat: 6.4698,
    lng: 3.5852,
    specialties: ["Internal Medicine", "Urology"],
    averageResponseTime: 32,
    peopleInQueue: 10,
    beds: 65,
    doctors: 22,
    averageConsultancyPrice: 13000,
  },
  {
    id: 6,
    name: "FirstCare Clinic Ajah",
    lat: 6.4876,
    lng: 3.6003,
    specialties: ["Pediatrics", "Dermatology"],
    averageResponseTime: 20,
    peopleInQueue: 4,
    beds: 45,
    doctors: 12,
    averageConsultancyPrice: 9500,
  },
  {
    id: 7,
    name: "Gracefield Medical Isolo",
    lat: 6.538,
    lng: 3.3212,
    specialties: ["Neurology", "Cardiology"],
    averageResponseTime: 45,
    peopleInQueue: 13,
    beds: 70,
    doctors: 26,
    averageConsultancyPrice: 17000,
  },
  {
    id: 8,
    name: "HopeLine Clinic Surulere",
    lat: 6.505,
    lng: 3.3499,
    specialties: ["Gynecology", "Psychiatry"],
    averageResponseTime: 38,
    peopleInQueue: 11,
    beds: 55,
    doctors: 17,
    averageConsultancyPrice: 14000,
  },
  {
    id: 9,
    name: "IslandCare General Hospital",
    lat: 6.4483,
    lng: 3.4216,
    specialties: ["Emergency", "General Medicine"],
    averageResponseTime: 18,
    peopleInQueue: 5,
    beds: 100,
    doctors: 35,
    averageConsultancyPrice: 12500,
  },
  {
    id: 10,
    name: "Jewel Hospital Yaba",
    lat: 6.5144,
    lng: 3.3792,
    specialties: ["Orthopedics", "Neurology"],
    averageResponseTime: 29,
    peopleInQueue: 8,
    beds: 58,
    doctors: 20,
    averageConsultancyPrice: 11500,
  },
  {
    id: 11,
    name: "Kingly Medical Centre",
    lat: 6.5167,
    lng: 3.3539,
    specialties: ["Cardiology", "Radiology"],
    averageResponseTime: 26,
    peopleInQueue: 6,
    beds: 62,
    doctors: 21,
    averageConsultancyPrice: 14500,
  },
  {
    id: 12,
    name: "Lagos State University Teaching Hospital (LASUTH)",
    lat: 6.599,
    lng: 3.3431,
    specialties: ["All Specialties"],
    averageResponseTime: 50,
    peopleInQueue: 20,
    beds: 200,
    doctors: 60,
    averageConsultancyPrice: 20000,
  },
  {
    id: 13,
    name: "Mercy Gate Hospital Mushin",
    lat: 6.534,
    lng: 3.352,
    specialties: ["ENT", "Ophthalmology"],
    averageResponseTime: 34,
    peopleInQueue: 7,
    beds: 40,
    doctors: 13,
    averageConsultancyPrice: 10500,
  },
  {
    id: 14,
    name: "New Dawn Medical Centre",
    lat: 6.4712,
    lng: 3.3745,
    specialties: ["Urology", "Nephrology"],
    averageResponseTime: 42,
    peopleInQueue: 10,
    beds: 65,
    doctors: 18,
    averageConsultancyPrice: 16000,
  },
  {
    id: 15,
    name: "Optimal Care Hospital",
    lat: 6.5049,
    lng: 3.3373,
    specialties: ["Obstetrics", "General Practice"],
    averageResponseTime: 22,
    peopleInQueue: 5,
    beds: 48,
    doctors: 14,
    averageConsultancyPrice: 9500,
  },
  {
    id: 16,
    name: "Peacehaven Clinic Ikorodu",
    lat: 6.6173,
    lng: 3.5075,
    specialties: ["Emergency", "Pediatrics"],
    averageResponseTime: 36,
    peopleInQueue: 8,
    beds: 72,
    doctors: 19,
    averageConsultancyPrice: 10000,
  },
  {
    id: 17,
    name: "Queen’s Specialist Hospital",
    lat: 6.447,
    lng: 3.512,
    specialties: ["Gynecology", "Fertility"],
    averageResponseTime: 31,
    peopleInQueue: 7,
    beds: 66,
    doctors: 16,
    averageConsultancyPrice: 15500,
  },
  {
    id: 18,
    name: "Royal Life Medical Centre",
    lat: 6.4435,
    lng: 3.46,
    specialties: ["Radiology", "Surgery"],
    averageResponseTime: 33,
    peopleInQueue: 9,
    beds: 59,
    doctors: 22,
    averageConsultancyPrice: 13500,
  },
  {
    id: 19,
    name: "Sunrise Hospital Badagry",
    lat: 6.4253,
    lng: 2.8877,
    specialties: ["General Medicine", "Public Health"],
    averageResponseTime: 39,
    peopleInQueue: 11,
    beds: 75,
    doctors: 20,
    averageConsultancyPrice: 9000,
  },
  {
    id: 20,
    name: "TruCare Clinic Victoria Island",
    lat: 6.4276,
    lng: 3.4411,
    specialties: ["ENT", "General Practice"],
    averageResponseTime: 27,
    peopleInQueue: 6,
    beds: 52,
    doctors: 18,
    averageConsultancyPrice: 14500,
  },
  {
    id: 21,
    name: "Unity Hospital Apapa",
    lat: 6.4443,
    lng: 3.3594,
    specialties: ["General Medicine", "Psychiatry"],
    averageResponseTime: 41,
    peopleInQueue: 10,
    beds: 60,
    doctors: 17,
    averageConsultancyPrice: 12000,
  },
  {
    id: 22,
    name: "Victory Specialist Hospital",
    lat: 6.5192,
    lng: 3.3965,
    specialties: ["Orthopedics", "Cardiology"],
    averageResponseTime: 37,
    peopleInQueue: 9,
    beds: 68,
    doctors: 23,
    averageConsultancyPrice: 15000,
  },
  {
    id: 23,
    name: "Wellcare Medical Centre",
    lat: 6.5083,
    lng: 3.3768,
    specialties: ["Dermatology", "Urology"],
    averageResponseTime: 28,
    peopleInQueue: 6,
    beds: 55,
    doctors: 15,
    averageConsultancyPrice: 11000,
  },
  {
    id: 24,
    name: "Xpress Hospital Gbagada",
    lat: 6.5661,
    lng: 3.3849,
    specialties: ["Cardiology", "ENT"],
    averageResponseTime: 24,
    peopleInQueue: 5,
    beds: 60,
    doctors: 19,
    averageConsultancyPrice: 12500,
  },
  {
    id: 25,
    name: "YoungLife Medical Ikoyi",
    lat: 6.4513,
    lng: 3.4532,
    specialties: ["General Surgery", "Pediatrics"],
    averageResponseTime: 26,
    peopleInQueue: 7,
    beds: 62,
    doctors: 20,
    averageConsultancyPrice: 14000,
  },
  {
    id: 26,
    name: "Zenith Health Clinic",
    lat: 6.4564,
    lng: 3.4156,
    specialties: ["Nephrology", "Radiology"],
    averageResponseTime: 38,
    peopleInQueue: 10,
    beds: 64,
    doctors: 21,
    averageConsultancyPrice: 15000,
  },
];
